services:
  - type: web
    name: rayitos-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"
    envVars:
      - key: FLASK_ENV
        value: production
